# Семинар 1

- про Jupyter Notebook: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/

## numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [1]:
import numpy as np

In [2]:
vec = np.array([[1, 2], [3, 4], [5, 6]], dtype='int64')

In [3]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
print(vec)

[[1 2]
 [3 4]
 [5 6]]


С чем мы работаем?

In [5]:
vec.dtype

dtype('int64')

In [6]:
type(vec)

numpy.ndarray

Размер массива:

In [7]:
vec.shape

(3, 2)

Число осей:

In [8]:
vec.ndim

2

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [9]:
np.sum(vec)

21

In [10]:
# по столбцам сумма
# axis - это измерение, которое мы схлопываем (в данном случае схлопываем строки)
np.sum(vec, axis=0)

array([ 9, 12])

In [11]:
# по строчкам сумма
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [12]:
vec.sum()

21

Транспонируем массив:

In [13]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [14]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Обратите внимание, что переменная `vec` не поменялась!

In [15]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Размеры массивов можно менять:

In [16]:
vec.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
# мы хотим привести данные к 3 столбцам, а сколько строчек - нам не важно
vec.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
vec.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

Индексирование:

In [19]:
# двоеточие просто копирует то, что было в измерении
vec[:, 1]

array([2, 4, 6])

In [20]:
vec[2, :]

array([5, 6])

In [21]:
vec[1:2, 0]

array([3])

In [22]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

In [23]:
vec[vec % 2 == 0]

array([2, 4, 6])

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [24]:
np.zeros((2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

Массив из единиц:

In [25]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Единичная матрица:

In [26]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Массивы можно объединять:

In [27]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
# склеивание по строчкам
np.hstack((vec, np.zeros(vec.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [5., 6., 0., 0.]])

In [29]:
# склеивание по столбцам
np.vstack((vec, np.zeros(vec.shape)))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

И, наконец - арифметические операции!

In [30]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [31]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [32]:
vec ** 2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [33]:
vec + vec ** 2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [34]:
vec * vec ** 2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [35]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

Матричное умножение:

In [36]:
vec.dot(vec ** 2)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [37]:
vec.dot((vec ** 2).T)

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [38]:
vec @ (vec ** 2).T

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [41]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [43]:
vec + np.arange(3).reshape(3, 1)

array([[1, 2],
       [4, 5],
       [7, 8]])

Генерация случайных чисел:

In [ ]:
np.random.rand(2, 3)

In [ ]:
np.random.seed(2019)
np.random.rand(2, 3)

In [ ]:
np.random.randn(3, 2)

In [ ]:
np.random.normal(2, 1, size=3)

In [ ]:
np.random.randint(5, 10, size=3)

Почему вообще используют `numpy`?

In [46]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [47]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

CPU times: user 31.6 s, sys: 112 ms, total: 31.7 s
Wall time: 31.8 s


In [48]:
%%time
C = A @ B

CPU times: user 5.37 ms, sys: 3.9 ms, total: 9.27 ms
Wall time: 4.15 ms


### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).
2. Найти максимальный нечетный элемент в массиве.
3. Замените все нечетные элементы массива на ваше любимое число.
4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*
5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_
6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_
7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [44]:
# 1
a = np.array([1,2,3,4,5,6,7])
a[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [46]:
# 2
max(a[a % 2 != 0])

7

In [47]:
# 3
a[a % 2 != 0] = 10
a

array([10,  2, 10,  4, 10,  6, 10])

In [61]:
# 4
def create(n):
    return np.arange(n*2 - 1, 0, -2) 

create(10)

array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [86]:
# 5
a = np.array([-9, -5, 1, 2, 3, 4])
n = -1.33
def find(a, n):
    diff = np.abs(a - n)
    return (a[np.argmin(diff)], a[np.argmax(diff)])

find(a, n)

(1, -9)

In [114]:
# 6
deriv = np.array([4, 6, 0, 1])
def coeff(deriv):
    deriv = deriv[::-1]
    answ = list(deriv  / (np.arange(len(deriv)) + 1))[::-1]
    answ.append(-2)
    return list(map(int, answ))

coeff(deriv)

[1, 2, 0, 1, -2]

In [208]:
# 7
coeff = np.array([1, 2, 0, 1, -2])
def calc_answ(coeff, x):
    coeff = coeff[::-1]
    powers = np.arange(len(coeff))
    deriv = list(coeff * powers)[1:]
    deriv_powers = np.arange(len(deriv))
    return sum((x ** np.arange(4)) * deriv)

calc_answ(coeff, 2)

57